// Form-prefill defaults for VGC 2026 Regulation Set M-B. M-A's entries carry
// over verbatim (M-B is a superset); the new rows below come from the M-B
// defaults CSV.
//
// Megas omit `ability` because the forme has a single forced ability — the
// dex layer falls back to `species.abilities[0]` in that case.

import type { SpeciesDefault } from '~/types/champions/regulation'
import type { Vgc2026_MBSpecies } from './vgc-2026-m-b'

export const vgc2026_MBDefaults = {
  Aegislash: { nature: 'Adamant', move: 'Poltergeist' },
  Aerodactyl: { nature: 'Jolly', move: 'Rock Slide', ability: 'Unnerve' },
  'Aerodactyl-Mega': { nature: 'Jolly', move: 'Rock Slide' },
  'Aggron-Mega': { nature: 'Careful', move: 'Body Press' },
  Annihilape: { nature: 'Adamant', move: 'Rage Fist', ability: 'Defiant' },
  'Arcanine-Hisui': { nature: 'Adamant', move: 'Flare Blitz', ability: 'Rock Head' },
  Archaludon: { nature: 'Modest', move: 'Electro Shot', ability: 'Stamina' },
  Azumarill: { nature: 'Adamant', move: 'Liquidation', ability: 'Huge Power' },
  'Barbaracle-Mega': { nature: 'Adamant', move: 'Close Combat' },
  Basculegion: { nature: 'Jolly', move: 'Wave Crash', ability: 'Adaptability' },
  'Blastoise-Mega': { nature: 'Modest', move: 'Water Spout' },
  'Blaziken-Mega': { nature: 'Jolly', move: 'Close Combat' },
  'Camerupt-Mega': { nature: 'Quiet', move: 'Heat Wave' },
  Ceruledge: { nature: 'Adamant', move: 'Bitter Blade', ability: 'Flash Fire' },
  'Charizard-Mega-X': { nature: 'Adamant', move: 'Flare Blitz' },
  'Charizard-Mega-Y': { nature: 'Modest', move: 'Heat Wave' },
  Corviknight: { nature: 'Impish', move: 'Brave Bird', ability: 'Mirror Armor' },
  'Crabominable-Mega': { nature: 'Brave', move: 'Ice Hammer' },
  'Delphox-Mega': { nature: 'Timid', move: 'Heat Wave' },
  Dragapult: { nature: 'Jolly', move: 'Dragon Darts', ability: 'Clear Body' },
  Dragonite: { nature: 'Adamant', move: 'Extreme Speed', ability: 'Inner Focus' },
  'Dragonite-Mega': { nature: 'Modest', move: 'Hurricane' },
  'Dragalge-Mega': { nature: 'Modest', move: 'Sludge Bomb' },
  'Drampa-Mega': { nature: 'Quiet', move: 'Hyper Voice' },
  // Champions-new 'Eelevate' ability isn't in @smogon/calc yet; stand in with
  // Levitate until the calc catches up.
  Eelektross: { nature: 'Modest', move: 'Thunder', ability: 'Levitate' },
  Excadrill: { nature: 'Adamant', move: 'Earthquake', ability: 'Sand Rush' },
  'Falinks-Mega': { nature: 'Adamant', move: 'Close Combat' },
  Farigiraf: { nature: 'Bold', move: 'Hyper Voice', ability: 'Armor Tail' },
  'Feraligatr-Mega': { nature: 'Adamant', move: 'Double-Edge' },
  'Floette-Mega': { nature: 'Modest', move: 'Moonblast' },
  'Froslass-Mega': { nature: 'Timid', move: 'Blizzard' },
  Garchomp: { nature: 'Adamant', move: 'Earthquake', ability: 'Rough Skin' },
  'Garchomp-Mega': { nature: 'Adamant', move: 'Earthquake' },
  'Gardevoir-Mega': { nature: 'Modest', move: 'Hyper Voice' },
  'Gengar-Mega': { nature: 'Timid', move: 'Shadow Ball' },
  Gholdengo: { nature: 'Modest', move: 'Make It Rain' },
  'Glimmora-Mega': { nature: 'Timid', move: 'Power Gem' },
  'Golurk-Mega': { nature: 'Brave', move: 'Poltergeist' },
  'Greninja-Mega': { nature: 'Timid', move: 'Dark Pulse' },
  Gyarados: { nature: 'Adamant', move: 'Waterfall', ability: 'Intimidate' },
  'Gyarados-Mega': { nature: 'Adamant', move: 'Waterfall' },
  Hatterene: { nature: 'Quiet', move: 'Dazzling Gleam', ability: 'Magic Bounce' },
  Houndstone: { nature: 'Adamant', move: 'Last Respects', ability: 'Sand Rush' },
  Hydreigon: { nature: 'Modest', move: 'Draco Meteor', ability: 'Levitate' },
  Incineroar: { nature: 'Careful', move: 'Flare Blitz', ability: 'Intimidate' },
  'Kangaskhan-Mega': { nature: 'Adamant', move: 'Double-Edge' },
  Kingambit: { nature: 'Adamant', move: 'Sucker Punch', ability: 'Defiant' },
  'Kommo-o': { nature: 'Modest', move: 'Clanging Scales', ability: 'Soundproof' },
  'Lopunny-Mega': { nature: 'Jolly', move: 'Close Combat' },
  'Lucario-Mega': { nature: 'Jolly', move: 'Close Combat' },
  'Malamar-Mega': { nature: 'Adamant', move: 'Psycho Cut' },
  Mamoswine: { nature: 'Adamant', move: 'Icicle Crash', ability: 'Oblivious' },
  'Mawile-Mega': { nature: 'Adamant', move: 'Play Rough' },
  'Meganium-Mega': { nature: 'Modest', move: 'Solar Beam' },
  Meowscarada: { nature: 'Adamant', move: 'Flower Trick', ability: 'Protean' },
  'Metagross-Mega': { nature: 'Jolly', move: 'Psychic Fangs' },
  Milotic: { nature: 'Bold', move: 'Scald', ability: 'Competitive' },
  Mimikyu: { nature: 'Adamant', move: 'Play Rough', ability: 'Disguise' },
  'Ninetales-Alola': { nature: 'Timid', move: 'Blizzard', ability: 'Snow Warning' },
  Orthworm: { nature: 'Impish', move: 'Body Press', ability: 'Earth Eater' },
  Overqwil: { nature: 'Adamant', move: 'Gunk Shot', ability: 'Intimidate' },
  Palafin: { nature: 'Adamant', move: 'Jet Punch' },
  Pelipper: { nature: 'Timid', move: 'Hurricane', ability: 'Drizzle' },
  Politoed: { nature: 'Modest', move: 'Weather Ball', ability: 'Drizzle' },
  Primarina: { nature: 'Modest', move: 'Hyper Voice', ability: 'Liquid Voice' },
  'Pyroar-Mega': { nature: 'Modest', move: 'Heat Wave' },
  'Raichu-Mega-X': { nature: 'Jolly', move: 'Volt Tackle' },
  'Raichu-Mega-Y': { nature: 'Timid', move: 'Zap Cannon' },
  'Rotom-Heat': { nature: 'Modest', move: 'Overheat', ability: 'Levitate' },
  'Rotom-Wash': { nature: 'Modest', move: 'Hydro Pump', ability: 'Levitate' },
  'Sceptile-Mega': { nature: 'Timid', move: 'Leaf Storm' },
  Scizor: { nature: 'Adamant', move: 'Bullet Punch', ability: 'Technician' },
  'Scizor-Mega': { nature: 'Adamant', move: 'Bullet Punch' },
  'Scolipede-Mega': { nature: 'Adamant', move: 'Gunk Shot' },
  'Scovillain-Mega': { nature: 'Calm', move: 'Overheat' },
  'Scrafty-Mega': { nature: 'Adamant', move: 'Close Combat' },
  Sinistcha: { nature: 'Bold', move: 'Matcha Gotcha', ability: 'Hospitality' },
  Sneasler: { nature: 'Adamant', move: 'Dire Claw', ability: 'Unburden' },
  'Staraptor-Mega': { nature: 'Jolly', move: 'Close Combat' },
  'Starmie-Mega': { nature: 'Adamant', move: 'Liquidation' },
  'Swampert-Mega': { nature: 'Adamant', move: 'Liquidation' },
  Sylveon: { nature: 'Modest', move: 'Hyper Voice', ability: 'Pixilate' },
  Talonflame: { nature: 'Jolly', move: 'Brave Bird', ability: 'Gale Wings' },
  'Tauros-Paldea-Aqua': { nature: 'Adamant', move: 'Close Combat', ability: 'Intimidate' },
  Tinkaton: { nature: 'Adamant', move: 'Gigaton Hammer', ability: 'Mold Breaker' },
  Torkoal: { nature: 'Quiet', move: 'Eruption', ability: 'Drought' },
  Tsareena: { nature: 'Adamant', move: 'Trop Kick', ability: 'Queenly Majesty' },
  'Typhlosion-Hisui': { nature: 'Modest', move: 'Eruption', ability: 'Blaze' },
  Tyranitar: { nature: 'Adamant', move: 'Rock Slide', ability: 'Sand Stream' },
  'Tyranitar-Mega': { nature: 'Adamant', move: 'Rock Slide' },
  Venusaur: { nature: 'Modest', move: 'Sludge Bomb', ability: 'Chlorophyll' },
  'Venusaur-Mega': { nature: 'Modest', move: 'Sludge Bomb' },
  Volcarona: { nature: 'Modest', move: 'Heat Wave', ability: 'Flame Body' },
  Whimsicott: { nature: 'Timid', move: 'Moonblast', ability: 'Prankster' },
  'Zoroark-Hisui': { nature: 'Timid', move: 'Hyper Voice', ability: 'Illusion' },
} as const satisfies Partial<Record<Vgc2026_MBSpecies, SpeciesDefault>>
