// Manually curated snapshot of VGC 2026 Regulation Set M-B. M-B is a superset
// of M-A: every M-A species/item stays legal, plus the additions documented in
// the M-B alias / defaults CSVs.
//
// Stat/type/ability data for the M-B Champions Megas now ships natively from
// `@pkmn/mods/champions` (0.10.10+). Their stones (Raichunite X/Y, Staraptite,
// Scolipite, Scraftinite, Pyroarite, Malamarite, Barbaracite, Dragalgite,
// Falinksite) are in `legalItems` below.

import type { Regulation } from '~/types/champions/regulation'
import { vgc2026_MBDefaults } from './vgc-2026-m-b-defaults'

const legalSpecies = [
    'Abomasnow',
    'Abomasnow-Mega',
    'Absol',
    'Absol-Mega',
    'Aegislash',
    'Aerodactyl',
    'Aerodactyl-Mega',
    'Aggron',
    'Aggron-Mega',
    'Alakazam',
    'Alakazam-Mega',
    'Alcremie',
    'Altaria',
    'Altaria-Mega',
    'Ampharos',
    'Ampharos-Mega',
    'Annihilape',
    'Appletun',
    'Araquanid',
    'Arbok',
    'Arcanine',
    'Arcanine-Hisui',
    'Archaludon',
    'Ariados',
    'Armarouge',
    'Aromatisse',
    'Audino',
    'Audino-Mega',
    'Aurorus',
    'Avalugg',
    'Avalugg-Hisui',
    'Azumarill',
    'Banette',
    'Banette-Mega',
    'Barbaracle',
    'Barbaracle-Mega',
    'Basculegion',
    'Basculegion-F',
    'Bastiodon',
    'Beartic',
    'Beedrill',
    'Beedrill-Mega',
    'Bellibolt',
    'Blastoise',
    'Blastoise-Mega',
    'Blaziken',
    'Blaziken-Mega',
    'Camerupt',
    'Camerupt-Mega',
    'Castform',
    'Ceruledge',
    'Chandelure',
    'Chandelure-Mega',
    'Charizard',
    'Charizard-Mega-X',
    'Charizard-Mega-Y',
    'Chesnaught',
    'Chesnaught-Mega',
    'Chimecho',
    'Chimecho-Mega',
    'Clawitzer',
    'Clefable',
    'Clefable-Mega',
    'Cofagrigus',
    'Conkeldurr',
    'Corviknight',
    'Crabominable',
    'Crabominable-Mega',
    'Cramorant-Gorging',
    'Cramorant-Gulping',
    'Decidueye',
    'Decidueye-Hisui',
    'Dedenne',
    'Delphox',
    'Delphox-Mega',
    'Diggersby',
    'Ditto',
    'Dragalge',
    'Dragalge-Mega',
    'Dragapult',
    'Dragonite',
    'Dragonite-Mega',
    'Drampa',
    'Drampa-Mega',
    'Eelektross',
    'Eelektross-Mega',
    'Emboar',
    'Emboar-Mega',
    'Emolga',
    'Empoleon',
    'Espathra',
    'Espeon',
    'Excadrill',
    'Excadrill-Mega',
    'Falinks',
    'Falinks-Mega',
    'Farigiraf',
    'Feraligatr',
    'Feraligatr-Mega',
    'Flapple',
    'Flareon',
    'Floette-Eternal',
    'Floette-Mega',
    'Florges',
    'Forretress',
    'Froslass',
    'Froslass-Mega',
    'Furfrou',
    'Gallade',
    'Gallade-Mega',
    'Garbodor',
    'Garchomp',
    'Garchomp-Mega',
    'Gardevoir',
    'Gardevoir-Mega',
    'Garganacl',
    'Gengar',
    'Gengar-Mega',
    'Gholdengo',
    'Glaceon',
    'Glalie',
    'Glalie-Mega',
    'Glimmora',
    'Glimmora-Mega',
    'Gliscor',
    'Golurk',
    'Golurk-Mega',
    'Goodra',
    'Goodra-Hisui',
    'Gourgeist',
    'Gourgeist-Large',
    'Gourgeist-Small',
    'Gourgeist-Super',
    'Greninja',
    'Greninja-Mega',
    'Grimmsnarl',
    'Gyarados',
    'Gyarados-Mega',
    'Hatterene',
    'Hawlucha',
    'Hawlucha-Mega',
    'Heliolisk',
    'Heracross',
    'Heracross-Mega',
    'Hippowdon',
    'Houndoom',
    'Houndoom-Mega',
    'Houndstone',
    'Hydrapple',
    'Hydreigon',
    'Incineroar',
    'Infernape',
    'Jolteon',
    'Kangaskhan',
    'Kangaskhan-Mega',
    'Kingambit',
    'Kleavor',
    'Klefki',
    'Kommo-o',
    'Krookodile',
    'Leafeon',
    'Liepard',
    'Lopunny',
    'Lopunny-Mega',
    'Lucario',
    'Lucario-Mega',
    'Luxray',
    'Lycanroc',
    'Lycanroc-Dusk',
    'Lycanroc-Midnight',
    'Machamp',
    'Malamar',
    'Malamar-Mega',
    'Mamoswine',
    'Manectric',
    'Manectric-Mega',
    'Maushold',
    'Maushold-Four',
    'Mawile',
    'Mawile-Mega',
    'Medicham',
    'Medicham-Mega',
    'Meganium',
    'Meganium-Mega',
    'Meloetta-Pirouette',
    'Meowscarada',
    'Meowstic',
    'Meowstic-F',
    'Meowstic-F-Mega',
    'Meowstic-M-Mega',
    'Metagross',
    'Metagross-Mega',
    'Milotic',
    'Mimikyu',
    'Mimikyu-Busted',
    'Minior-Meteor',
    'Morpeko',
    'Morpeko-Hangry',
    'Mr. Rime',
    'Mudsdale',
    'Ninetales',
    'Ninetales-Alola',
    'Noivern',
    'Oranguru',
    'Orthworm',
    'Overqwil',
    'Palafin',
    'Palafin-Hero',
    'Pangoro',
    'Passimian',
    'Pelipper',
    'Pidgeot',
    'Pidgeot-Mega',
    'Pikachu',
    'Pinsir',
    'Pinsir-Mega',
    'Politoed',
    'Polteageist',
    'Polteageist-Antique',
    'Primarina',
    'Pyroar',
    'Pyroar-Mega',
    'Quaquaval',
    'Raichu',
    'Raichu-Alola',
    'Raichu-Mega-X',
    'Raichu-Mega-Y',
    'Rampardos',
    'Reuniclus',
    'Rhyperior',
    'Roserade',
    'Rotom',
    'Rotom-Fan',
    'Rotom-Frost',
    'Rotom-Heat',
    'Rotom-Mow',
    'Rotom-Wash',
    'Runerigus',
    'Sableye',
    'Sableye-Mega',
    'Salazzle',
    'Samurott',
    'Samurott-Hisui',
    'Sandaconda',
    'Sceptile',
    'Sceptile-Mega',
    'Scizor',
    'Scizor-Mega',
    'Scolipede',
    'Scolipede-Mega',
    'Scovillain',
    'Scovillain-Mega',
    'Scrafty',
    'Scrafty-Mega',
    'Serperior',
    'Sharpedo',
    'Sharpedo-Mega',
    'Simipour',
    'Simisage',
    'Simisear',
    'Sinistcha',
    'Sinistcha-Masterpiece',
    'Skarmory',
    'Skarmory-Mega',
    'Skeledirge',
    'Slowbro',
    'Slowbro-Galar',
    'Slowbro-Mega',
    'Slowking',
    'Slowking-Galar',
    'Slurpuff',
    'Sneasler',
    'Snorlax',
    'Spiritomb',
    'Staraptor',
    'Staraptor-Mega',
    'Starmie',
    'Starmie-Mega',
    'Steelix',
    'Steelix-Mega',
    'Stunfisk',
    'Stunfisk-Galar',
    'Swampert',
    'Swampert-Mega',
    'Sylveon',
    'Talonflame',
    'Tauros',
    'Tauros-Paldea-Aqua',
    'Tauros-Paldea-Blaze',
    'Tauros-Paldea-Combat',
    'Tinkaton',
    'Torkoal',
    'Torterra',
    'Toucannon',
    'Toxapex',
    'Toxicroak',
    'Trevenant',
    'Tsareena',
    'Typhlosion',
    'Typhlosion-Hisui',
    'Tyranitar',
    'Tyranitar-Mega',
    'Tyrantrum',
    'Umbreon',
    'Vanilluxe',
    'Vaporeon',
    'Venusaur',
    'Venusaur-Mega',
    'Victreebel',
    'Victreebel-Mega',
    'Vivillon',
    'Vivillon-Fancy',
    'Vivillon-Pokeball',
    'Volcarona',
    'Watchog',
    'Weavile',
    'Whimsicott',
    'Wyrdeer',
    'Zoroark',
    'Zoroark-Hisui',
] as const

const legalItems = [
    'Abomasite',
    'Absolite',
    'Aerodactylite',
    'Aggronite',
    'Alakazite',
    'Altarianite',
    'Ampharosite',
    'Aspear Berry',
    'Audinite',
    'Babiri Berry',
    'Banettite',
    'Barbaracite',
    'Beedrillite',
    'Big Root',
    'Black Belt',
    'Black Glasses',
    'Blastoisinite',
    'Blazikenite',
    'Bright Powder',
    'Cameruptite',
    'Chandelurite',
    'Charcoal',
    'Charizardite X',
    'Charizardite Y',
    'Charti Berry',
    'Cheri Berry',
    'Chesnaughtite',
    'Chesto Berry',
    'Chilan Berry',
    'Chimechite',
    'Choice Scarf',
    'Chople Berry',
    'Clefablite',
    'Coba Berry',
    'Colbur Berry',
    'Crabominite',
    'Damp Rock',
    'Delphoxite',
    'Dragalgite',
    'Dragon Fang',
    'Dragoninite',
    'Drampanite',
    'Eelektrossite',
    'Emboarite',
    'Excadrite',
    'Expert Belt',
    'Fairy Feather',
    'Falinksite',
    'Feraligite',
    'Floettite',
    'Focus Band',
    'Focus Sash',
    'Froslassite',
    'Galladite',
    'Garchompite',
    'Gardevoirite',
    'Gengarite',
    'Glalitite',
    'Glimmoranite',
    'Golurkite',
    'Greninjite',
    'Gyaradosite',
    'Haban Berry',
    'Hard Stone',
    'Hawluchanite',
    'Heat Rock',
    'Heracronite',
    'Houndoominite',
    'Icy Rock',
    'Iron Ball',
    'Kangaskhanite',
    'Kasib Berry',
    'Kebia Berry',
    "King's Rock",
    'Leftovers',
    'Leppa Berry',
    'Life Orb',
    'Light Ball',
    'Light Clay',
    'Lopunnite',
    'Lucarionite',
    'Lum Berry',
    'Magnet',
    'Malamarite',
    'Manectite',
    'Mawilite',
    'Medichamite',
    'Meganiumite',
    'Mental Herb',
    'Meowsticite',
    'Metagrossite',
    'Metal Coat',
    'Metronome',
    'Miracle Seed',
    'Muscle Band',
    'Mystic Water',
    'Never-Melt Ice',
    'Occa Berry',
    'Oran Berry',
    'Passho Berry',
    'Payapa Berry',
    'Pecha Berry',
    'Persim Berry',
    'Pidgeotite',
    'Pinsirite',
    'Poison Barb',
    'Pyroarite',
    'Quick Claw',
    'Raichunite X',
    'Raichunite Y',
    'Rawst Berry',
    'Rindo Berry',
    'Roseli Berry',
    'Sablenite',
    'Sceptilite',
    'Scizorite',
    'Scolipite',
    'Scope Lens',
    'Scovillainite',
    'Scraftinite',
    'Sharp Beak',
    'Sharpedonite',
    'Shed Shell',
    'Shell Bell',
    'Shuca Berry',
    'Silk Scarf',
    'Silver Powder',
    'Sitrus Berry',
    'Skarmorite',
    'Slowbronite',
    'Smooth Rock',
    'Soft Sand',
    'Spell Tag',
    'Staraptite',
    'Starminite',
    'Steelixite',
    'Swampertite',
    'Tanga Berry',
    'Twisted Spoon',
    'Tyranitarite',
    'Venusaurite',
    'Victreebelite',
    'Wacan Berry',
    'White Herb',
    'Wide Lens',
    'Wise Glasses',
    'Yache Berry',
    'Zoom Lens',
] as const

export type Vgc2026_MBSpecies = (typeof legalSpecies)[number]
export type Vgc2026_MBItem = (typeof legalItems)[number]

export const vgc2026_MB = {
  id: 'vgc2026_MB',
  name: 'VGC 2026 Regulation Set M-B',
  legalSpecies,
  legalItems,
  legalMechanics: ['mega-evolution'] as const,
  speciesDefaults: vgc2026_MBDefaults,
} as const satisfies Regulation
