// Form-prefill defaults for VGC 2026 Regulation Set M-A. One curated nature /
// signature move / ability per species, sourced from common Reg M-A spreads.
// Megas omit `ability` because the forme has a single forced ability — the
// dex layer falls back to `species.abilities[0]` in that case.

import type { SpeciesDefault } from '~/types/champions/regulation'
import type { Vgc2026_MASpecies } from './vgc-2026-m-a'

export const vgc2026_MADefaults = {
  Aegislash: { nature: 'Adamant', move: 'Poltergeist' },
  Aerodactyl: { nature: 'Jolly', move: 'Rock Slide', ability: 'Unnerve' },
  'Aerodactyl-Mega': { nature: 'Jolly', move: 'Rock Slide' },
  'Aggron-Mega': { nature: 'Careful', move: 'Body Press' },
  'Arcanine-Hisui': { nature: 'Adamant', move: 'Flare Blitz', ability: 'Rock Head' },
  Archaludon: { nature: 'Modest', move: 'Electro Shot', ability: 'Stamina' },
  Basculegion: { nature: 'Jolly', move: 'Wave Crash', ability: 'Adaptability' },
  'Blastoise-Mega': { nature: 'Modest', move: 'Water Spout' },
  'Camerupt-Mega': { nature: 'Quiet', move: 'Heat Wave' },
  Ceruledge: { nature: 'Adamant', move: 'Bitter Blade', ability: 'Flash Fire' },
  'Charizard-Mega-X': { nature: 'Adamant', move: 'Flare Blitz' },
  'Charizard-Mega-Y': { nature: 'Modest', move: 'Heat Wave' },
  Corviknight: { nature: 'Impish', move: 'Brave Bird', ability: 'Mirror Armor' },
  'Crabominable-Mega': { nature: 'Brave', move: 'Ice Hammer' },
  'Delphox-Mega': { nature: 'Timid', move: 'Heat Wave' },
  Dragapult: { nature: 'Jolly', move: 'Dragon Darts', ability: 'Clear Body' },
  Dragonite: { nature: 'Adamant', move: 'Extreme Speed', ability: 'Inner Focus' },
  'Dragonite-Mega': { nature: 'Modest', move: 'Hurricane' },
  'Drampa-Mega': { nature: 'Quiet', move: 'Hyper Voice' },
  Excadrill: { nature: 'Adamant', move: 'Earthquake', ability: 'Sand Rush' },
  Farigiraf: { nature: 'Bold', move: 'Hyper Voice', ability: 'Armor Tail' },
  'Feraligatr-Mega': { nature: 'Adamant', move: 'Double-Edge' },
  'Floette-Mega': { nature: 'Modest', move: 'Moonblast' },
  'Froslass-Mega': { nature: 'Timid', move: 'Blizzard' },
  Garchomp: { nature: 'Adamant', move: 'Earthquake', ability: 'Rough Skin' },
  'Garchomp-Mega': { nature: 'Adamant', move: 'Earthquake' },
  'Gardevoir-Mega': { nature: 'Modest', move: 'Hyper Voice' },
  'Gengar-Mega': { nature: 'Timid', move: 'Shadow Ball' },
  'Glimmora-Mega': { nature: 'Timid', move: 'Power Gem' },
  'Golurk-Mega': { nature: 'Brave', move: 'Poltergeist' },
  'Greninja-Mega': { nature: 'Timid', move: 'Dark Pulse' },
  Gyarados: { nature: 'Adamant', move: 'Waterfall', ability: 'Intimidate' },
  'Gyarados-Mega': { nature: 'Adamant', move: 'Waterfall' },
  Hatterene: { nature: 'Quiet', move: 'Dazzling Gleam', ability: 'Magic Bounce' },
  Hydreigon: { nature: 'Modest', move: 'Draco Meteor', ability: 'Levitate' },
  Incineroar: { nature: 'Careful', move: 'Flare Blitz', ability: 'Intimidate' },
  'Kangaskhan-Mega': { nature: 'Adamant', move: 'Double-Edge' },
  Kingambit: { nature: 'Adamant', move: 'Sucker Punch', ability: 'Defiant' },
  'Kommo-o': { nature: 'Modest', move: 'Clanging Scales', ability: 'Soundproof' },
  'Lopunny-Mega': { nature: 'Jolly', move: 'Close Combat' },
  'Lucario-Mega': { nature: 'Jolly', move: 'Close Combat' },
  Mamoswine: { nature: 'Adamant', move: 'Icicle Crash', ability: 'Oblivious' },
  'Meganium-Mega': { nature: 'Modest', move: 'Solar Beam' },
  Meowscarada: { nature: 'Adamant', move: 'Flower Trick', ability: 'Protean' },
  Milotic: { nature: 'Bold', move: 'Scald', ability: 'Competitive' },
  Mimikyu: { nature: 'Adamant', move: 'Play Rough', ability: 'Disguise' },
  'Ninetales-Alola': { nature: 'Timid', move: 'Blizzard', ability: 'Snow Warning' },
  Orthworm: { nature: 'Impish', move: 'Body Press', ability: 'Earth Eater' },
  Palafin: { nature: 'Adamant', move: 'Jet Punch' },
  Pelipper: { nature: 'Timid', move: 'Hurricane', ability: 'Drizzle' },
  Politoed: { nature: 'Modest', move: 'Weather Ball', ability: 'Drizzle' },
  Primarina: { nature: 'Modest', move: 'Hyper Voice', ability: 'Liquid Voice' },
  'Rotom-Heat': { nature: 'Modest', move: 'Overheat', ability: 'Levitate' },
  'Rotom-Wash': { nature: 'Modest', move: 'Hydro Pump', ability: 'Levitate' },
  Scizor: { nature: 'Adamant', move: 'Bullet Punch', ability: 'Technician' },
  'Scizor-Mega': { nature: 'Adamant', move: 'Bullet Punch' },
  'Scovillain-Mega': { nature: 'Calm', move: 'Overheat' },
  Sinistcha: { nature: 'Bold', move: 'Matcha Gotcha', ability: 'Hospitality' },
  Sneasler: { nature: 'Adamant', move: 'Dire Claw', ability: 'Unburden' },
  'Starmie-Mega': { nature: 'Adamant', move: 'Liquidation' },
  Sylveon: { nature: 'Modest', move: 'Hyper Voice', ability: 'Pixilate' },
  Talonflame: { nature: 'Jolly', move: 'Brave Bird', ability: 'Gale Wings' },
  'Tauros-Paldea-Aqua': { nature: 'Adamant', move: 'Close Combat', ability: 'Intimidate' },
  Tinkaton: { nature: 'Adamant', move: 'Gigaton Hammer', ability: 'Mold Breaker' },
  Torkoal: { nature: 'Quiet', move: 'Eruption', ability: 'Drought' },
  Tsareena: { nature: 'Adamant', move: 'Trop Kick', ability: 'Queenly Majesty' },
  'Typhlosion-Hisui': { nature: 'Modest', move: 'Eruption', ability: 'Blaze' },
  Tyranitar: { nature: 'Adamant', move: 'Rock Slide', ability: 'Sand Stream' },
  'Tyranitar-Mega': { nature: 'Adamant', move: 'Rock Slide' },
  Venusaur: { nature: 'Modest', move: 'Sludge Bomb', ability: 'Chlorophyll' },
  'Venusaur-Mega': { nature: 'Modest', move: 'Sludge Bomb' },
  Volcarona: { nature: 'Modest', move: 'Heat Wave', ability: 'Flame Body' },
  Whimsicott: { nature: 'Timid', move: 'Moonblast', ability: 'Prankster' },
  'Zoroark-Hisui': { nature: 'Timid', move: 'Hyper Voice', ability: 'Illusion' },
} as const satisfies Partial<Record<Vgc2026_MASpecies, SpeciesDefault>>
