// Manually curated snapshot of VGC 2026 Regulation Set M-A. To regenerate
// from the current @pkmn/mods/champions dex:
//   pnpm tsx packages/shared-types/scripts/snapshot-regulation.ts
// When the next regulation drops and the mod is slow to update, hand-edit
// this file (or copy it to a sibling — e.g. vgc-2026-m-b.ts — and re-point
// currentRegulation in ./index.ts).

import type { Regulation } from '../../../types/champions/regulation'

export const vgc2026_MA = {
  id: 'vgc2026_MA',
  name: 'VGC 2026 Regulation Set M-A',
  legalSpecies: [
    "Abomasnow",
    "Abomasnow-Mega",
    "Absol",
    "Absol-Mega",
    "Aegislash",
    "Aerodactyl",
    "Aerodactyl-Mega",
    "Aggron",
    "Aggron-Mega",
    "Alakazam",
    "Alakazam-Mega",
    "Alcremie",
    "Altaria",
    "Altaria-Mega",
    "Ampharos",
    "Ampharos-Mega",
    "Appletun",
    "Araquanid",
    "Arbok",
    "Arcanine",
    "Arcanine-Hisui",
    "Archaludon",
    "Ariados",
    "Armarouge",
    "Aromatisse",
    "Audino",
    "Audino-Mega",
    "Aurorus",
    "Avalugg",
    "Avalugg-Hisui",
    "Azumarill",
    "Banette",
    "Banette-Mega",
    "Basculegion",
    "Basculegion-F",
    "Bastiodon",
    "Beartic",
    "Beedrill",
    "Beedrill-Mega",
    "Bellibolt",
    "Blastoise",
    "Blastoise-Mega",
    "Camerupt",
    "Camerupt-Mega",
    "Castform",
    "Ceruledge",
    "Chandelure",
    "Chandelure-Mega",
    "Charizard",
    "Charizard-Mega-X",
    "Charizard-Mega-Y",
    "Chesnaught",
    "Chesnaught-Mega",
    "Chimecho",
    "Chimecho-Mega",
    "Clawitzer",
    "Clefable",
    "Clefable-Mega",
    "Cofagrigus",
    "Conkeldurr",
    "Corviknight",
    "Crabominable",
    "Crabominable-Mega",
    "Cramorant-Gorging",
    "Cramorant-Gulping",
    "Decidueye",
    "Decidueye-Hisui",
    "Dedenne",
    "Delphox",
    "Delphox-Mega",
    "Diggersby",
    "Ditto",
    "Dragapult",
    "Dragonite",
    "Dragonite-Mega",
    "Drampa",
    "Drampa-Mega",
    "Eiscue-Noice",
    "Emboar",
    "Emboar-Mega",
    "Emolga",
    "Empoleon",
    "Espathra",
    "Espeon",
    "Excadrill",
    "Excadrill-Mega",
    "Farigiraf",
    "Feraligatr",
    "Feraligatr-Mega",
    "Flapple",
    "Flareon",
    "Floette-Eternal",
    "Floette-Mega",
    "Florges",
    "Forretress",
    "Froslass",
    "Froslass-Mega",
    "Furfrou",
    "Gallade",
    "Gallade-Mega",
    "Garbodor",
    "Garchomp",
    "Garchomp-Mega",
    "Gardevoir",
    "Gardevoir-Mega",
    "Garganacl",
    "Gengar",
    "Gengar-Mega",
    "Glaceon",
    "Glalie",
    "Glalie-Mega",
    "Glimmora",
    "Glimmora-Mega",
    "Gliscor",
    "Golurk",
    "Golurk-Mega",
    "Goodra",
    "Goodra-Hisui",
    "Gourgeist",
    "Gourgeist-Large",
    "Gourgeist-Small",
    "Gourgeist-Super",
    "Greninja",
    "Greninja-Mega",
    "Gyarados",
    "Gyarados-Mega",
    "Hatterene",
    "Hawlucha",
    "Hawlucha-Mega",
    "Heliolisk",
    "Heracross",
    "Heracross-Mega",
    "Hippowdon",
    "Houndoom",
    "Houndoom-Mega",
    "Hydrapple",
    "Hydreigon",
    "Incineroar",
    "Infernape",
    "Jolteon",
    "Kangaskhan",
    "Kangaskhan-Mega",
    "Kingambit",
    "Kleavor",
    "Klefki",
    "Kommo-o",
    "Krookodile",
    "Leafeon",
    "Liepard",
    "Lopunny",
    "Lopunny-Mega",
    "Lucario",
    "Lucario-Mega",
    "Luxray",
    "Lycanroc",
    "Lycanroc-Dusk",
    "Lycanroc-Midnight",
    "Machamp",
    "Mamoswine",
    "Manectric",
    "Manectric-Mega",
    "Maushold",
    "Maushold-Four",
    "Medicham",
    "Medicham-Mega",
    "Meganium",
    "Meganium-Mega",
    "Meloetta-Pirouette",
    "Meowscarada",
    "Meowstic",
    "Meowstic-F",
    "Meowstic-F-Mega",
    "Meowstic-M-Mega",
    "Milotic",
    "Mimikyu",
    "Mimikyu-Busted",
    "Minior-Meteor",
    "Morpeko",
    "Morpeko-Hangry",
    "Mr. Rime",
    "Mudsdale",
    "Ninetales",
    "Ninetales-Alola",
    "Noivern",
    "Ogerpon-Cornerstone-Tera",
    "Ogerpon-Hearthflame-Tera",
    "Ogerpon-Teal-Tera",
    "Ogerpon-Wellspring-Tera",
    "Oranguru",
    "Orthworm",
    "Palafin",
    "Palafin-Hero",
    "Pangoro",
    "Passimian",
    "Pelipper",
    "Pidgeot",
    "Pidgeot-Mega",
    "Pikachu",
    "Pinsir",
    "Pinsir-Mega",
    "Politoed",
    "Polteageist",
    "Polteageist-Antique",
    "Primarina",
    "Quaquaval",
    "Raichu",
    "Raichu-Alola",
    "Rampardos",
    "Reuniclus",
    "Rhyperior",
    "Roserade",
    "Rotom",
    "Rotom-Fan",
    "Rotom-Frost",
    "Rotom-Heat",
    "Rotom-Mow",
    "Rotom-Wash",
    "Runerigus",
    "Sableye",
    "Sableye-Mega",
    "Salazzle",
    "Samurott",
    "Samurott-Hisui",
    "Sandaconda",
    "Scizor",
    "Scizor-Mega",
    "Scovillain",
    "Scovillain-Mega",
    "Serperior",
    "Sharpedo",
    "Sharpedo-Mega",
    "Simipour",
    "Simisage",
    "Simisear",
    "Sinistcha",
    "Sinistcha-Masterpiece",
    "Skarmory",
    "Skarmory-Mega",
    "Skeledirge",
    "Slowbro",
    "Slowbro-Galar",
    "Slowbro-Mega",
    "Slowking",
    "Slowking-Galar",
    "Slurpuff",
    "Sneasler",
    "Snorlax",
    "Spiritomb",
    "Starmie",
    "Starmie-Mega",
    "Steelix",
    "Steelix-Mega",
    "Stunfisk",
    "Stunfisk-Galar",
    "Sylveon",
    "Talonflame",
    "Tauros",
    "Tauros-Paldea-Aqua",
    "Tauros-Paldea-Blaze",
    "Tauros-Paldea-Combat",
    "Terapagos-Terastal",
    "Tinkaton",
    "Torkoal",
    "Torterra",
    "Toucannon",
    "Toxapex",
    "Toxicroak",
    "Trevenant",
    "Tsareena",
    "Typhlosion",
    "Typhlosion-Hisui",
    "Tyranitar",
    "Tyranitar-Mega",
    "Tyrantrum",
    "Umbreon",
    "Vanilluxe",
    "Vaporeon",
    "Venusaur",
    "Venusaur-Mega",
    "Victreebel",
    "Victreebel-Mega",
    "Vivillon",
    "Vivillon-Fancy",
    "Vivillon-Pokeball",
    "Volcarona",
    "Watchog",
    "Weavile",
    "Whimsicott",
    "Wyrdeer",
    "Zoroark",
    "Zoroark-Hisui",
  ] as const,
  legalItems: [
    "Abomasite",
    "Absolite",
    "Aerodactylite",
    "Aggronite",
    "Alakazite",
    "Altarianite",
    "Ampharosite",
    "Aspear Berry",
    "Audinite",
    "Babiri Berry",
    "Banettite",
    "Beedrillite",
    "Black Belt",
    "Black Glasses",
    "Blastoisinite",
    "Bright Powder",
    "Cameruptite",
    "Chandelurite",
    "Charcoal",
    "Charizardite X",
    "Charizardite Y",
    "Charti Berry",
    "Cheri Berry",
    "Chesnaughtite",
    "Chesto Berry",
    "Chilan Berry",
    "Chimechite",
    "Choice Scarf",
    "Chople Berry",
    "Clefablite",
    "Coba Berry",
    "Colbur Berry",
    "Crabominite",
    "Delphoxite",
    "Dragon Fang",
    "Dragoninite",
    "Drampanite",
    "Emboarite",
    "Excadrite",
    "Fairy Feather",
    "Feraligite",
    "Floettite",
    "Focus Band",
    "Focus Sash",
    "Froslassite",
    "Galladite",
    "Garchompite",
    "Gardevoirite",
    "Gengarite",
    "Glalitite",
    "Glimmoranite",
    "Golurkite",
    "Greninjite",
    "Gyaradosite",
    "Haban Berry",
    "Hard Stone",
    "Hawluchanite",
    "Heracronite",
    "Houndoominite",
    "Kangaskhanite",
    "Kasib Berry",
    "Kebia Berry",
    "King's Rock",
    "Leftovers",
    "Leppa Berry",
    "Light Ball",
    "Lopunnite",
    "Lucarionite",
    "Lum Berry",
    "Magnet",
    "Manectite",
    "Medichamite",
    "Meganiumite",
    "Mental Herb",
    "Meowsticite",
    "Metal Coat",
    "Miracle Seed",
    "Mystic Water",
    "Never-Melt Ice",
    "Occa Berry",
    "Oran Berry",
    "Passho Berry",
    "Payapa Berry",
    "Pecha Berry",
    "Persim Berry",
    "Pidgeotite",
    "Pinsirite",
    "Poison Barb",
    "Quick Claw",
    "Rawst Berry",
    "Rindo Berry",
    "Roseli Berry",
    "Sablenite",
    "Scizorite",
    "Scope Lens",
    "Scovillainite",
    "Sharp Beak",
    "Sharpedonite",
    "Shell Bell",
    "Shuca Berry",
    "Silk Scarf",
    "Silver Powder",
    "Sitrus Berry",
    "Skarmorite",
    "Slowbronite",
    "Soft Sand",
    "Spell Tag",
    "Starminite",
    "Steelixite",
    "Tanga Berry",
    "Twisted Spoon",
    "Tyranitarite",
    "Venusaurite",
    "Victreebelite",
    "Wacan Berry",
    "White Herb",
    "Yache Berry",
  ] as const,
  legalMechanics: ['mega-evolution'] as const,
} as const satisfies Regulation

export type Vgc2026_MASpecies = (typeof vgc2026_MA.legalSpecies)[number]
export type Vgc2026_MAItem = (typeof vgc2026_MA.legalItems)[number]
