import type { AllItemName } from '~/types/champions/regulation'

export const itemAliases = {
  'Assault Vest': ['vest', 'av'],
  'Black Glasses': ['glasses'],
  Charcoal: ['charc'],
  'Choice Band': ['band'],
  'Choice Scarf': ['scarf'],
  'Choice Specs': ['specs'],
  'Dragon Fang': ['fang'],
  'Fairy Feather': ['feather', 'FF'],
  'Focus Sash': ['sash'],
  'Hard Stone': ['stone'],
  'Heavy-Duty Boots': ['boots', 'hdb'],
  Leftovers: ['lefties'],
  'Life Orb': ['orb', 'lo', 'plate'],
  'Light Ball': ['LB'],
  'Lum Berry': ['lum'],
  'Metal Coat': ['MC'],
  'Miracle Seed': ['MS'],
  'Mystic Water': ['MW'],
  'Never-Melt Ice': ['NMI'],
  'Poison Barb': ['barb'],
  'Sharp Beak': ['beak'],
  'Silk Scarf': ['silk'],
  'Silver Powder': ['powder'],
  'Sitrus Berry': ['sitrus'],
  'Twisted Spoon': ['spoon'],
} as const satisfies Partial<Record<AllItemName, readonly string[]>>
