import type { AllMoveName } from '~/types/champions/regulation'

export const moveAliases = {
  'Aerial Ace': ['AA'],
  'Aqua Jet': ['jet', 'AJ', 'AJet'],
  'Aura Sphere': ['ASphere'],
  Blizzard: ['blizz'],
  'Body Press': ['BP', 'Press'],
  'Brave Bird': ['BB'],
  'Breaking Swipe': ['BS', 'BSwipe'],
  'Close Combat': ['CC'],
  'Dazzling Gleam': ['DG', 'DGleam', 'Gleam'],
  'Draco Meteor': ['DM', 'Draco'],
  'Dragon Claw': ['DClaw'],
  'Dragon Pulse': ['DPulse'],
  'Drain Punch': ['DP'],
  'Dual Wingbeat': ['DWB', 'DW', 'Wingbeat'],
  'Earth Power': ['EP'],
  Earthquake: ['eq', 'quake'],
  'Electro Shot': ['ES', 'EShot'],
  Electroweb: ['EW', 'web', 'EWeb'],
  'Expanding Force': ['EF', 'EForce', 'Psyspam'],
  'Extreme Speed': ['Espeed'],
  'Fake Out': ['FO'],
  'Fiery Dance': ['FD'],
  'Final Gambit': ['FG'],
  'Flare Blitz': ['Blitz', 'FB'],
  'Flip Turn': ['FT'],
  'Foul Play': ['FP'],
  'Giga Drain': ['Giga', 'Gdrain'],
  'Gigaton Hammer': ['GHammer', 'GTH', 'Gigaton'],
  'Head Smash': ['HSmash', 'Smash'],
  'Heat Wave': ['HW', 'HWave'],
  'High Jump Kick': ['HJK'],
  'Hydro Pump': ['Pump', 'Hydro'],
  'Hyper Beam': ['HB'],
  'Hyper Voice': ['HV', 'HVoice'],
  'Ice Hammer': ['IHammer'],
  'Ice Punch': ['IP'],
  'Icy Wind': ['IW'],
  'Iron Head': ['IH'],
  'Jet Punch': ['JP'],
  'Kowtow Cleave': ['KC', 'Kowtoe', 'KTC'],
  'Last Respects': ['LR', 'Respects', 'Respect'],
  'Lava Plume': ['LP'],
  'Light of Ruin': ['LoR'],
  'Low Kick': ['LK'],
  'Matcha Gotcha': ['MG'],
  Moonblast: ['MB'],
  Overheat: ['OH'],
  'Phantom Force': ['PF', 'PForce'],
  Poltergeist: ['Polt'],
  'Power Gem': ['PGem', 'PG', 'Gem'],
  'Power Whip': ['PW', 'PWhip'],
  'Quick Attack': ['QA'],
  'Rock Slide': ['RS', 'Slide'],
  'Shadow Ball': ['SB'],
  'Shadow Sneak': ['SS'],
  'Sludge Bomb': ['Sludge', 'SBomb'],
  'Sucker Punch': ['SP', 'Sucker'],
  'Triple Axel': ['TA', 'Axel'],
  'Trop Kick': ['TK'],
  'U-turn': ['UT'],
  'Volt Switch': ['VS', 'Volt'],
  'Water Spout': ['WS', 'Spout'],
  'Wave Crash': ['WC'],
  'Weather Ball': ['WBall'],
  'Zen Headbutt': ['ZH'],
} as const satisfies Partial<Record<AllMoveName, readonly string[]>>
