import type { AllSpeciesName } from '~/types/champions/regulation'

export const speciesAliases = {
  Aerodactyl: ['Aero'],
  Aggron: ['The Wall'],
  Alakazam: ['Zam'],
  Annihilape: ['Ape'],
  Arcanine: ['Arc'],
  'Arcanine-Hisui': [
    'Harc',
    'HArc',
    'Hisuian Arcanine',
    'Hisuian-Arcanine',
    'Hisui Arcanine',
    'Hisui-Arcanine',
    'Arcanine Hisuian',
  ],
  Archaludon: ['Arch'],
  'Avalugg-Hisui': [
    'Hisuian Avalugg',
    'Hisuian-Avalugg',
    'Hisui Avalugg',
    'Hisui-Avalugg',
    'Avalugg Hisuian',
  ],
  Barbaracle: ['Barb', 'Barnacle'],
  Basculegion: ['Basc', 'BascM', 'Basc-M'],
  'Basculegion-F': ['Basc-F', 'BascF'],
  Blastoise: ['Stoise'],
  Blaziken: ['Blaz'],
  Charizard: ['Zard', 'Char'],
  Clefable: ['Clef', 'Cleff'],
  Conkeldurr: ['Conk'],
  Corviknight: ['Corv', 'Corvi'],
  Crabominable: ['Crab'],
  'Decidueye-Hisui': [
    'Hisuian Decidueye',
    'Hisuian-Decidueye',
    'Hisui Decidueye',
    'Hisui-Decidueye',
    'Decidueye Hisuian',
  ],
  Dragalge: ['Drag', 'Algae', 'Alge'],
  Dragapult: ['Pult'],
  Dragonite: ['Dnite'],
  Eelektross: ['Eel'],
  Excadrill: ['Exca', 'Drill'],
  Farigiraf: ['Fari', 'Farig', 'giraf'],
  Feraligatr: ['Gator', 'gatr'],
  Froslass: ['Fross', 'Fros', 'Lass'],
  Garchomp: ['Chomp'],
  Gardevoir: ['Gard', 'Garde'],
  Garganacl: ['Garg'],
  Gholdengo: ['Gold', 'Ghold'],
  Glimmora: ['Glimm', 'Glim'],
  'Goodra-Hisui': [
    'Hisuian Goodra',
    'Hisuian-Goodra',
    'Hisui Goodra',
    'Hisui-Goodra',
    'Goodra Hisuian',
  ],
  Greninja: ['Gren'],
  Grimmsnarl: ['Grimm', 'Grim'],
  Gyarados: ['Gyara'],
  Hatterene: ['Hat', 'Hatt'],
  Heracross: ['Hera'],
  Hippowdon: ['Hippo'],
  Houndstone: ['Hound', 'HStone'],
  Incineroar: ['Incin', 'GOAT', 'Wolfe'],
  Kangaskhan: ['Kang', 'Kanga'],
  Kingambit: ['Gambit', 'Cringegambit', 'KG'],
  'Kommo-o': ['Kommo', 'komo', 'komoo', 'komo o', 'komo-o'],
  Krookodile: ['Krook'],
  Lopunny: ['bunny'],
  Luxray: ['Lux'],
  Machamp: ['Champ'],
  Malamar: ['Mar', 'Mala'],
  Mamoswine: ['Mamo'],
  Maushold: ['Maus', 'Mouse'],
  Mawile: ['Maw'],
  // Mega Meowstic is identical across genders; default the bare
  // 'Meowstic-Mega' to the female form.
  'Meowstic-F-Mega': ['Meowstic-Mega'],
  Metagross: ['Meta', 'Mgross'],
  Milotic: ['Milli', 'Milly', 'Milo'],
  Ninetales: ['Ninetails'],
  'Ninetales-Alola': [
    'Ninetails-Alola',
    'Ninetails-A',
    'ANinetails',
    'NinetailsA',
    'Alolan Ninetales',
    'Alolan-Ninetales',
    'Alola Ninetales',
    'Alola-Ninetales',
    'Ninetales Alolan',
    'Alolan Ninetails',
    'Alolan-Ninetails',
    'Alola Ninetails',
    'Alola-Ninetails',
    'Ninetails Alola',
    'Ninetails Alolan',
  ],
  Orthworm: ['Orth', 'worm'],
  Overqwil: ['qwil', 'Overq'],
  Palafin: ['Pala'],
  Pelipper: ['Peli'],
  Politoed: ['Poli', 'toed'],
  Raichu: ['Chu', 'Rai'],
  'Raichu-Alola': [
    'Alolan Raichu',
    'Alolan-Raichu',
    'Alola Raichu',
    'Alola-Raichu',
    'Raichu Alolan',
  ],
  'Rotom-Fan': ['Rotom-Flying', 'Rotom-Fly', 'Fan'],
  'Rotom-Frost': [
    'Rotom-F',
    'Rotom-Fridge',
    'Fridge',
    'Rotom Fridge',
    'Rotom-Ice',
    'Rotom-I',
  ],
  'Rotom-Heat': ['Rotom-H', 'Rotom-Oven', 'Oven', 'Rotom-Fire'],
  'Rotom-Mow': ['Rotom-M', 'Rotom-Mower', 'Mower', 'Rotom-Grass', 'Rotom-G'],
  'Rotom-Wash': ['Rotom-W', 'Rotom-Washer', 'Washer', 'Wash', 'Rotom-Water'],
  Sableye: ['Sable'],
  'Samurott-Hisui': [
    'HSamurott',
    'Samurott-H',
    'Hamurott',
    'SamurottH',
    'Hisuian Samurott',
    'Hisuian-Samurott',
    'Hisui Samurott',
    'Hisui-Samurott',
    'Samurott Hisuian',
  ],
  Sceptile: ['Scept', 'Scep'],
  Scolipede: ['Scol', 'Scoli', 'Pede'],
  Scovillain: ['Scov', 'Scovi'],
  Sharpedo: ['Shark'],
  Simipour: ['pour'],
  Simisage: ['sage'],
  Simisear: ['sear'],
  Sinistcha: ['Sini', 'matcha', 'cha'],
  Skarmory: ['Skarm'],
  Skeledirge: ['dirge', 'Skele', 'Skelly'],
  Slowbro: ['bro'],
  'Slowbro-Galar': [
    'Glowbro',
    'Slowbro-G',
    'GSlowbro',
    'SlowbroG',
    'Globro',
    'Galarian Slowbro',
    'Galarian-Slowbro',
    'Galar Slowbro',
    'Galar-Slowbro',
    'Slowbro Galarian',
  ],
  'Slowking-Galar': [
    'Glowking',
    'Slowking-G',
    'GSlowking',
    'SlowkingG',
    'Gloking',
    'Galarian Slowking',
    'Galarian-Slowking',
    'Galar Slowking',
    'Galar-Slowking',
    'Slowking Galarian',
  ],
  Staraptor: ['Raptor'],
  'Stunfisk-Galar': [
    'Galarian Stunfisk',
    'Galarian-Stunfisk',
    'Galar Stunfisk',
    'Galar-Stunfisk',
    'Stunfisk Galarian',
  ],
  Swampert: ['Pert', 'Swamp'],
  Sylveon: ['Sylv'],
  Talonflame: ['Talon'],
  'Tauros-Paldea-Aqua': [
    'Tauros-Water',
    'Tauros-PA',
    'Tauros-P-A',
    'TaurosPA',
    'Tauros-P Water',
    'TaurosP Water',
    'TaurosWater',
  ],
  'Tauros-Paldea-Blaze': [
    'Tauros-Fire',
    'Tauros-PB',
    'Tauros-P-B',
    'TaurosPB',
    'Tauros-P Fire',
    'TaurosP Fire',
    'TaurosFire',
  ],
  'Tauros-Paldea-Combat': [
    'Tauros-Fighting',
    'Tauros-PC',
    'Tauros-P-C',
    'TaurosPC',
    'Tauros-P Fight',
    'TaurosP Fighting',
    'TaurosFight',
  ],
  Tinkaton: ['Tink', 'Tinkywinky'],
  Torkoal: ['Turtle', 'Tork'],
  Toxapex: ['Pex'],
  Tsareena: ['Tsar', 'Sareena'],
  'Typhlosion-Hisui': [
    'HTyphlosion',
    'Typhlosion-H',
    'TyphlosionH',
    'Hyphlosion',
    'Hisuian Typhlosion',
    'Hisuian-Typhlosion',
    'Hisui Typhlosion',
    'Hisui-Typhlosion',
    'Typhlosion Hisuian',
    'H-Typhlosian',
  ],
  Tyranitar: ['Ttar'],
  Vanilluxe: ['Vani', 'Vanilla'],
  Venusaur: ['Venu'],
  Vivillon: ['Vivillion'],
  Volcarona: ['Volc'],
  Watchog: ['Watchhog'],
  Whimsicott: ['Whims'],
  Wyrdeer: ['Wyrd'],
  Zoroark: ['Zorark', 'Zoro'],
  'Zoroark-Hisui': [
    'Zoroark-H',
    'ZoroarkH',
    'HZoroark',
    'H-Zoroark',
    'Horoark',
    'Zorark-H',
    'ZorarkH',
    'HZorark',
    'H-Zorark',
    'Horarrk',
    'Hisuian Zoroark',
    'Hisuian-Zoroark',
    'Hisui Zoroark',
    'Hisui-Zoroark',
    'Zoroark Hisuian',
  ],
} as const satisfies Partial<Record<AllSpeciesName, readonly string[]>>
