// Snapshot the full @pkmn/dex (gen 9) species, item, and move names. Powers
// the AllSpeciesName / AllItemName / AllMoveName literal-union constraints.
// Re-run when @pkmn/dex bumps to pick up new entries.
//
// Usage:
//   pnpm tsx packages/shared-types/scripts/snapshot-all-names.ts species \
//     > packages/shared-types/src/constants/all-species.ts
//   pnpm tsx packages/shared-types/scripts/snapshot-all-names.ts items \
//     > packages/shared-types/src/constants/all-items.ts
//   pnpm tsx packages/shared-types/scripts/snapshot-all-names.ts moves \
//     > packages/shared-types/src/constants/all-moves.ts

import { Dex } from '@pkmn/dex'

const which = process.argv[2]

const print = (varName: string, values: readonly string[]): void => {
  const lines = values.map((v) => `  ${JSON.stringify(v)},`).join('\n')
  process.stdout.write(
    [
      '// AUTO-GENERATED by scripts/snapshot-all-names.ts — do not hand-edit.',
      `// ${values.length} entries.`,
      '',
      `export const ${varName} = [`,
      lines,
      '] as const',
      '',
    ].join('\n'),
  )
}

if (which === 'species') {
  const names = Dex.species
    .all()
    .map((s) => s.name)
    .toSorted()
  print('allSpeciesNames', names)
} else if (which === 'items') {
  const names = Dex.items
    .all()
    .map((i) => i.name)
    .toSorted()
  print('allItemNames', names)
} else if (which === 'moves') {
  const names = Dex.moves
    .all()
    .map((m) => m.name)
    .toSorted()
  print('allMoveNames', names)
} else {
  process.stderr.write(`usage: snapshot-all-names.ts species|items|moves\n`)
  process.exit(1)
}
