// Champions Mega species not yet present in @pkmn/dex (and absent from
// @pkmn/mods/champions's Pokedex/Species table — that mod ships them only
// as FormatsData legality entries, with no stats/types/abilities).

import type { ModData } from '@pkmn/dex'

export const championsMegaSpeciesPatch: NonNullable<ModData['Species']> = {
  clefablemega: {
    num: 36,
    name: 'Clefable-Mega',
    baseSpecies: 'Clefable',
    forme: 'Mega',
    types: ['Fairy', 'Flying'],
    baseStats: { hp: 95, atk: 80, def: 93, spa: 135, spd: 110, spe: 70 },
    abilities: { 0: 'Magic Bounce' },
    weightkg: 42.3,
    eggGroups: ['Fairy'],
    requiredItem: 'Clefablite',
  },
  victreebelmega: {
    num: 71,
    name: 'Victreebel-Mega',
    baseSpecies: 'Victreebel',
    forme: 'Mega',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 80, atk: 125, def: 85, spa: 135, spd: 95, spe: 70 },
    abilities: { 0: 'Innards Out' },
    weightkg: 125.5,
    eggGroups: ['Grass'],
    requiredItem: 'Victreebelite',
  },
  starmiemega: {
    num: 121,
    name: 'Starmie-Mega',
    baseSpecies: 'Starmie',
    forme: 'Mega',
    types: ['Water', 'Psychic'],
    baseStats: { hp: 60, atk: 100, def: 105, spa: 130, spd: 105, spe: 120 },
    abilities: { 0: 'Huge Power' },
    weightkg: 80,
    eggGroups: ['Water 3'],
    requiredItem: 'Starminite',
  },
  dragonitemega: {
    num: 149,
    name: 'Dragonite-Mega',
    baseSpecies: 'Dragonite',
    forme: 'Mega',
    types: ['Dragon', 'Flying'],
    baseStats: { hp: 91, atk: 124, def: 115, spa: 145, spd: 125, spe: 100 },
    abilities: { 0: 'Multiscale' },
    weightkg: 290,
    eggGroups: ['Water 1', 'Dragon'],
    requiredItem: 'Dragoninite',
  },
  meganiummega: {
    num: 154,
    name: 'Meganium-Mega',
    baseSpecies: 'Meganium',
    forme: 'Mega',
    types: ['Grass', 'Fairy'],
    baseStats: { hp: 80, atk: 92, def: 115, spa: 143, spd: 115, spe: 80 },
    abilities: { 0: 'Mega Sol' },
    weightkg: 201,
    eggGroups: ['Monster', 'Grass'],
    requiredItem: 'Meganiumite',
  },
  feraligatrmega: {
    num: 160,
    name: 'Feraligatr-Mega',
    baseSpecies: 'Feraligatr',
    forme: 'Mega',
    types: ['Water', 'Dragon'],
    baseStats: { hp: 85, atk: 160, def: 125, spa: 89, spd: 93, spe: 78 },
    abilities: { 0: 'Dragonize' },
    weightkg: 108.8,
    eggGroups: ['Monster', 'Water 1'],
    requiredItem: 'Feraligite',
  },
  skarmorymega: {
    num: 227,
    name: 'Skarmory-Mega',
    baseSpecies: 'Skarmory',
    forme: 'Mega',
    types: ['Steel', 'Flying'],
    baseStats: { hp: 65, atk: 140, def: 110, spa: 40, spd: 100, spe: 110 },
    abilities: { 0: 'Stalwart' },
    weightkg: 40.4,
    eggGroups: ['Flying'],
    requiredItem: 'Skarmorite',
  },
  chimechomega: {
    num: 358,
    name: 'Chimecho-Mega',
    baseSpecies: 'Chimecho',
    forme: 'Mega',
    types: ['Psychic', 'Steel'],
    baseStats: { hp: 75, atk: 50, def: 110, spa: 135, spd: 120, spe: 65 },
    abilities: { 0: 'Levitate' },
    weightkg: 8,
    eggGroups: ['Amorphous'],
    requiredItem: 'Chimechite',
  },
  froslassmega: {
    num: 478,
    name: 'Froslass-Mega',
    baseSpecies: 'Froslass',
    forme: 'Mega',
    types: ['Ice', 'Ghost'],
    baseStats: { hp: 70, atk: 80, def: 70, spa: 140, spd: 100, spe: 120 },
    abilities: { 0: 'Snow Warning' },
    weightkg: 29.6,
    eggGroups: ['Fairy', 'Mineral'],
    requiredItem: 'Froslassite',
  },
  emboarmega: {
    num: 500,
    name: 'Emboar-Mega',
    baseSpecies: 'Emboar',
    forme: 'Mega',
    types: ['Fire', 'Fighting'],
    baseStats: { hp: 110, atk: 148, def: 75, spa: 110, spd: 110, spe: 75 },
    abilities: { 0: 'Mold Breaker' },
    weightkg: 180.3,
    eggGroups: ['Field'],
    requiredItem: 'Emboarite',
  },
  excadrillmega: {
    num: 530,
    name: 'Excadrill-Mega',
    baseSpecies: 'Excadrill',
    forme: 'Mega',
    types: ['Ground', 'Steel'],
    baseStats: { hp: 110, atk: 165, def: 100, spa: 65, spd: 65, spe: 103 },
    abilities: { 0: 'Piercing Drill' },
    weightkg: 60,
    eggGroups: ['Field'],
    requiredItem: 'Excadrite',
  },
  chandeluremega: {
    num: 609,
    name: 'Chandelure-Mega',
    baseSpecies: 'Chandelure',
    forme: 'Mega',
    types: ['Fire', 'Ghost'],
    baseStats: { hp: 60, atk: 75, def: 110, spa: 175, spd: 110, spe: 90 },
    abilities: { 0: 'Infiltrator' },
    weightkg: 69.6,
    eggGroups: ['Amorphous'],
    requiredItem: 'Chandelurite',
  },
  golurkmega: {
    num: 623,
    name: 'Golurk-Mega',
    baseSpecies: 'Golurk',
    forme: 'Mega',
    types: ['Ground', 'Ghost'],
    baseStats: { hp: 89, atk: 159, def: 105, spa: 70, spd: 105, spe: 55 },
    abilities: { 0: 'Unseen Fist' },
    weightkg: 330,
    eggGroups: ['Mineral'],
    requiredItem: 'Golurkite',
  },
  chesnaughtmega: {
    num: 652,
    name: 'Chesnaught-Mega',
    baseSpecies: 'Chesnaught',
    forme: 'Mega',
    types: ['Grass', 'Fighting'],
    baseStats: { hp: 88, atk: 137, def: 172, spa: 74, spd: 115, spe: 44 },
    abilities: { 0: 'Bulletproof' },
    weightkg: 90,
    eggGroups: ['Field'],
    requiredItem: 'Chesnaughtite',
  },
  delphoxmega: {
    num: 655,
    name: 'Delphox-Mega',
    baseSpecies: 'Delphox',
    forme: 'Mega',
    types: ['Fire', 'Psychic'],
    baseStats: { hp: 75, atk: 69, def: 72, spa: 159, spd: 125, spe: 134 },
    abilities: { 0: 'Levitate' },
    weightkg: 39,
    eggGroups: ['Field'],
    requiredItem: 'Delphoxite',
  },
  greninjamega: {
    num: 658,
    name: 'Greninja-Mega',
    baseSpecies: 'Greninja',
    forme: 'Mega',
    types: ['Water', 'Dark'],
    baseStats: { hp: 72, atk: 125, def: 77, spa: 133, spd: 81, spe: 142 },
    abilities: { 0: 'Protean' },
    weightkg: 40,
    eggGroups: ['Water 1'],
    requiredItem: 'Greninjite',
  },
  // The mega-stone holder is Floette-Eternal (not regular Floette), but the
  // canonical mega name used elsewhere in this repo is 'Floette-Mega'.
  floettemega: {
    num: 670,
    name: 'Floette-Mega',
    baseSpecies: 'Floette-Eternal',
    forme: 'Mega',
    types: ['Fairy'],
    baseStats: { hp: 74, atk: 85, def: 87, spa: 155, spd: 148, spe: 102 },
    abilities: { 0: 'Fairy Aura' },
    weightkg: 100.8,
    eggGroups: ['Undiscovered'],
    requiredItem: 'Floettite',
  },
  meowsticmmega: {
    num: 678,
    name: 'Meowstic-M-Mega',
    baseSpecies: 'Meowstic',
    forme: 'Mega',
    types: ['Psychic'],
    baseStats: { hp: 74, atk: 48, def: 76, spa: 143, spd: 101, spe: 124 },
    abilities: { 0: 'Trace' },
    weightkg: 10.1,
    eggGroups: ['Field'],
    requiredItem: 'Meowsticite',
  },
  meowsticfmega: {
    num: 678,
    name: 'Meowstic-F-Mega',
    baseSpecies: 'Meowstic-F',
    forme: 'Mega',
    types: ['Psychic'],
    baseStats: { hp: 74, atk: 48, def: 76, spa: 143, spd: 101, spe: 124 },
    abilities: { 0: 'Trace' },
    weightkg: 10.1,
    eggGroups: ['Field'],
    requiredItem: 'Meowsticite',
  },
  hawluchamega: {
    num: 701,
    name: 'Hawlucha-Mega',
    baseSpecies: 'Hawlucha',
    forme: 'Mega',
    types: ['Fighting', 'Flying'],
    baseStats: { hp: 78, atk: 137, def: 100, spa: 74, spd: 93, spe: 118 },
    abilities: { 0: 'No Guard' },
    weightkg: 25,
    eggGroups: ['Flying', 'Human-Like'],
    requiredItem: 'Hawluchanite',
  },
  crabominablemega: {
    num: 740,
    name: 'Crabominable-Mega',
    baseSpecies: 'Crabominable',
    forme: 'Mega',
    types: ['Fighting', 'Ice'],
    baseStats: { hp: 97, atk: 157, def: 122, spa: 62, spd: 107, spe: 33 },
    abilities: { 0: 'Iron Fist' },
    weightkg: 252.8,
    eggGroups: ['Water 3'],
    requiredItem: 'Crabominite',
  },
  drampamega: {
    num: 780,
    name: 'Drampa-Mega',
    baseSpecies: 'Drampa',
    forme: 'Mega',
    types: ['Normal', 'Dragon'],
    baseStats: { hp: 78, atk: 85, def: 110, spa: 160, spd: 116, spe: 36 },
    abilities: { 0: 'Berserk' },
    weightkg: 240.5,
    eggGroups: ['Monster', 'Dragon'],
    requiredItem: 'Drampanite',
  },
  scovillainmega: {
    num: 952,
    name: 'Scovillain-Mega',
    baseSpecies: 'Scovillain',
    forme: 'Mega',
    types: ['Grass', 'Fire'],
    baseStats: { hp: 65, atk: 138, def: 85, spa: 138, spd: 85, spe: 75 },
    abilities: { 0: 'Spicy Spray' },
    weightkg: 22,
    eggGroups: ['Grass'],
    requiredItem: 'Scovillainite',
  },
  glimmoramega: {
    num: 970,
    name: 'Glimmora-Mega',
    baseSpecies: 'Glimmora',
    forme: 'Mega',
    types: ['Rock', 'Poison'],
    baseStats: { hp: 83, atk: 90, def: 105, spa: 150, spd: 96, spe: 101 },
    abilities: { 0: 'Adaptability' },
    weightkg: 77,
    eggGroups: ['Mineral'],
    requiredItem: 'Glimmoranite',
  },
}
